In [6]:
# Pandas Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). 
# It is similar to a column in a spreadsheet or a SQL table. 
# Each element in a Series has an associated label, which can be used to access the data.

pip install pandas

SyntaxError: invalid syntax (1010276839.py, line 5)

In [7]:
import pandas as pd

hikes = pd.Series([7.5, 16.0, 12.0, 10.3], 
                   index=['Alice', 'Bob', 'Charlie', 'David'],
                   name='EmployeeHike')
print(hikes)

Alice       7.5
Bob        16.0
Charlie    12.0
David      10.3
Name: EmployeeHike, dtype: float64

In [8]:
hikes > 6

Alice      True
Bob        True
Charlie    True
David      True
Name: EmployeeHike, dtype: bool

In [9]:
hikes[hikes>6]

Alice       7.5
Bob        16.0
Charlie    12.0
David      10.3
Name: EmployeeHike, dtype: float64

In [10]:
#pandas DataFrame is a two-dimensional labeled data structure with columns of potentially different types. 
# It is similar to a spreadsheet or SQL table. 
# A DataFrame can be thought of as a collection of Series objects that share the same index. 
# Each column in a DataFrame can be of a different data type (e.g., integers, strings, floating point numbers, etc.).

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Experience': [2,4,6,8]
}
print(data)

{'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 35, 40], 'Experience': [2, 4, 6, 8]}

In [11]:
df= pd.DataFrame(data)
print(df)

      Name  Age  Experience
0    Alice   25           2
1      Bob   30           4
2  Charlie   35           6
3    David   40           8

In [12]:
#df.head() # to view the first few rows of the DataFrame

df.head()

      Name  Age  Experience
0    Alice   25           2
1      Bob   30           4
2  Charlie   35           6
3    David   40           8

In [13]:
df.head(2) # to view the first 2 rows of the DataFrame

    Name  Age  Experience
0  Alice   25           2
1    Bob   30           4

In [14]:
df.tail(2) # to view the last 2 rows of the DataFrame

      Name  Age  Experience
2  Charlie   35           6
3    David   40           8

In [15]:
df.shape # to view the number of rows and columns in the DataFrame

(4, 3)

In [16]:
df.dtypes # to view the data types of each column in the DataFrame

Name            str
Age           int64
Experience    int64
dtype: object

In [17]:
df.info() # to view a summary of the DataFrame, including the number of non-null values and data types of each column

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      str
 1   Age         4 non-null      int64
 2   Experience  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [18]:
df.describe() # to view summary statistics of the numerical columns in the DataFrame

             Age  Experience
count   4.000000    4.000000
mean   32.500000    5.000000
std     6.454972    2.581989
min    25.000000    2.000000
25%    28.750000    3.500000
50%    32.500000    5.000000
75%    36.250000    6.500000
max    40.000000    8.000000

In [19]:
import numpy as np

n=50
df=pd.DataFrame({
    'emp_id': range(1000, 1000+n),
    'name': [f'Employee_{i}' for i in range(n)],
    'age': np.random.randint(20, 60, size=n),
    'department': np.random.choice(['Engineering', 'HR', 'Sales'], n),
     'rating':np.random.choice([1,2,3,4,5],n),
     'salary': np.random.randint(50000, 150000, size=n)
    
})
df

    emp_id         name  age   department  rating  salary
0     1000   Employee_0   41        Sales       5   70113
1     1001   Employee_1   45           HR       4  133204
2     1002   Employee_2   37  Engineering       3   87700
3     1003   Employee_3   46  Engineering       3   98109
4     1004   Employee_4   54        Sales       1   81980
5     1005   Employee_5   22           HR       1   80512
6     1006   Employee_6   27        Sales       5   72953
7     1007   Employee_7   30  Engineering       3   72443
8     1008   Employee_8   38        Sales       1  148875
9     1009   Employee_9   55  Engineering       3  122175
10    1010  Employee_10   40        Sales       5   86804
11    1011  Employee_11   56        Sales       2  106474
12    1012  Employee_12   23  Engineering       2   91988
13    1013  Employee_13   53  Engineering       2  146583
14    1014  Employee_14   52  Engineering       4   84231
15    1015  Employee_15   54        Sales       3   93160
16    1016  Employee_16   26  Engineering       4  104076
17    1017  Employee_17   39        Sales       5   74967
18    1018  Employee_18   35           HR       1   69098
19    1019  Employee_19   26           HR       3  126059
20    1020  Employee_20   55        Sales       1   56743
21    1021  Employee_21   24  Engineering       5  122964
22    1022  Employee_22   52  Engineering       2   52005
23    1023  Employee_23   54           HR       5   76848
24    1024  Employee_24   29        Sales       1  107493
25    1025  Employee_25   47        Sales       3  141296
26    1026  Employee_26   40  Engineering       3   56350
27    1027  Employee_27   57        Sales       4  123778
28    1028  Employee_28   24           HR       1   88453
29    1029  Employee_29   32        Sales       2   77903
30    1030  Employee_30   31  Engineering       1   67104
31    1031  Employee_31   45        Sales       5   98361
32    1032  Employee_32   25  Engineering       1  135844
33    1033  Employee_33   36           HR       3  143457
34    1034  Employee_34   28  Engineering       2   88430
35    1035  Employee_35   35           HR       4   67336
36    1036  Employee_36   33        Sales       2  139486
37    1037  Employee_37   35           HR       4  107955
38    1038  Employee_38   57  Engineering       4   66261
39    1039  Employee_39   41        Sales       5  113415
40    1040  Employee_40   58        Sales       5   72292
41    1041  Employee_41   25           HR       5  119589
42    1042  Employee_42   23  Engineering       3  120989
43    1043  Employee_43   41           HR       4   77007
44    1044  Employee_44   24           HR       2  111542
45    1045  Employee_45   29        Sales       5  135408
46    1046  Employee_46   28        Sales       5  117186
47    1047  Employee_47   52        Sales       4  142967
48    1048  Employee_48   53  Engineering       1   92122
49    1049  Employee_49   29        Sales       4   80870

In [20]:
df[[ 'name','rating']].head()

         name  rating
0  Employee_0       5
1  Employee_1       4
2  Employee_2       3
3  Employee_3       3
4  Employee_4       1

In [21]:
#df.loc[0:2, ['name', 'rating']] # to select specific rows and columns using labels
df.loc[1:3, ['name', 'rating']]

         name  rating
1  Employee_1       4
2  Employee_2       3
3  Employee_3       3

In [22]:
#df.iloc[0:3, 0:2] # to select specific rows and columns using integer-based indexing
df.iloc[0].to_dict()

{'emp_id': 1000,
 'name': 'Employee_0',
 'age': 41,
 'department': 'Sales',
 'rating': 5,
 'salary': 70113}

In [23]:
df.iloc[-2:, :3]

    emp_id         name  age
48    1048  Employee_48   53
49    1049  Employee_49   29

In [24]:
#df[df['rating' > 3] ] # to filter rows based on a condition
df[df['rating'] > 3]

    emp_id         name  age   department  rating  salary
0     1000   Employee_0   41        Sales       5   70113
1     1001   Employee_1   45           HR       4  133204
6     1006   Employee_6   27        Sales       5   72953
10    1010  Employee_10   40        Sales       5   86804
14    1014  Employee_14   52  Engineering       4   84231
16    1016  Employee_16   26  Engineering       4  104076
17    1017  Employee_17   39        Sales       5   74967
21    1021  Employee_21   24  Engineering       5  122964
23    1023  Employee_23   54           HR       5   76848
27    1027  Employee_27   57        Sales       4  123778
31    1031  Employee_31   45        Sales       5   98361
35    1035  Employee_35   35           HR       4   67336
37    1037  Employee_37   35           HR       4  107955
38    1038  Employee_38   57  Engineering       4   66261
39    1039  Employee_39   41        Sales       5  113415
40    1040  Employee_40   58        Sales       5   72292
41    1041  Employee_41   25           HR       5  119589
43    1043  Employee_43   41           HR       4   77007
45    1045  Employee_45   29        Sales       5  135408
46    1046  Employee_46   28        Sales       5  117186
47    1047  Employee_47   52        Sales       4  142967
49    1049  Employee_49   29        Sales       4   80870

In [25]:
#df[df['Age'].between(30, 40)] # to filter rows where the 'Age' column is between 30 and 40 (inclusive)
df[df['age'].between(30, 40)]

    emp_id         name  age   department  rating  salary
2     1002   Employee_2   37  Engineering       3   87700
7     1007   Employee_7   30  Engineering       3   72443
8     1008   Employee_8   38        Sales       1  148875
10    1010  Employee_10   40        Sales       5   86804
17    1017  Employee_17   39        Sales       5   74967
18    1018  Employee_18   35           HR       1   69098
26    1026  Employee_26   40  Engineering       3   56350
29    1029  Employee_29   32        Sales       2   77903
30    1030  Employee_30   31  Engineering       1   67104
33    1033  Employee_33   36           HR       3  143457
35    1035  Employee_35   35           HR       4   67336
36    1036  Employee_36   33        Sales       2  139486
37    1037  Employee_37   35           HR       4  107955

In [26]:
#df[df[].isin] # to filter rows where the 'department' column is either 'Engineering' or 'Sales'
df[df['department'].isin(['Engineering', 'Sales'])]

    emp_id         name  age   department  rating  salary
0     1000   Employee_0   41        Sales       5   70113
2     1002   Employee_2   37  Engineering       3   87700
3     1003   Employee_3   46  Engineering       3   98109
4     1004   Employee_4   54        Sales       1   81980
6     1006   Employee_6   27        Sales       5   72953
7     1007   Employee_7   30  Engineering       3   72443
8     1008   Employee_8   38        Sales       1  148875
9     1009   Employee_9   55  Engineering       3  122175
10    1010  Employee_10   40        Sales       5   86804
11    1011  Employee_11   56        Sales       2  106474
12    1012  Employee_12   23  Engineering       2   91988
13    1013  Employee_13   53  Engineering       2  146583
14    1014  Employee_14   52  Engineering       4   84231
15    1015  Employee_15   54        Sales       3   93160
16    1016  Employee_16   26  Engineering       4  104076
17    1017  Employee_17   39        Sales       5   74967
20    1020  Employee_20   55        Sales       1   56743
21    1021  Employee_21   24  Engineering       5  122964
22    1022  Employee_22   52  Engineering       2   52005
24    1024  Employee_24   29        Sales       1  107493
25    1025  Employee_25   47        Sales       3  141296
26    1026  Employee_26   40  Engineering       3   56350
27    1027  Employee_27   57        Sales       4  123778
29    1029  Employee_29   32        Sales       2   77903
30    1030  Employee_30   31  Engineering       1   67104
31    1031  Employee_31   45        Sales       5   98361
32    1032  Employee_32   25  Engineering       1  135844
34    1034  Employee_34   28  Engineering       2   88430
36    1036  Employee_36   33        Sales       2  139486
38    1038  Employee_38   57  Engineering       4   66261
39    1039  Employee_39   41        Sales       5  113415
40    1040  Employee_40   58        Sales       5   72292
42    1042  Employee_42   23  Engineering       3  120989
45    1045  Employee_45   29        Sales       5  135408
46    1046  Employee_46   28        Sales       5  117186
47    1047  Employee_47   52        Sales       4  142967
48    1048  Employee_48   53  Engineering       1   92122
49    1049  Employee_49   29        Sales       4   80870

In [27]:
df['Bonus'] = df['salary'] * 0.1
df.head()

   emp_id        name  age   department  rating  salary    Bonus
0    1000  Employee_0   41        Sales       5   70113   7011.3
1    1001  Employee_1   45           HR       4  133204  13320.4
2    1002  Employee_2   37  Engineering       3   87700   8770.0
3    1003  Employee_3   46  Engineering       3   98109   9810.9
4    1004  Employee_4   54        Sales       1   81980   8198.0

In [30]:
df['exp_yr'] = df['rating']
print(df)

    emp_id         name  age   department  rating  salary  Bonus  exp_yr
0     1000   Employee_0   41        Sales       5   70113      5       5
1     1001   Employee_1   45           HR       4  133204      4       4
2     1002   Employee_2   37  Engineering       3   87700      3       3
3     1003   Employee_3   46  Engineering       3   98109      3       3
4     1004   Employee_4   54        Sales       1   81980      1       1
5     1005   Employee_5   22           HR       1   80512      1       1
6     1006   Employee_6   27        Sales       5   72953      5       5
7     1007   Employee_7   30  Engineering       3   72443      3       3
8     1008   Employee_8   38        Sales       1  148875      1       1
9     1009   Employee_9   55  Engineering       3  122175      3       3
10    1010  Employee_10   40        Sales       5   86804      5       5
11    1011  Employee_11   56        Sales       2  106474      2       2
12    1012  Employee_12   23  Engineering       2   91988      2       2
13    1013  Employee_13   53  Engineering       2  146583      2       2
14    1014  Employee_14   52  Engineering       4   84231      4       4
15    1015  Employee_15   54        Sales       3   93160      3       3
16    1016  Employee_16   26  Engineering       4  104076      4       4
17    1017  Employee_17   39        Sales       5   74967      5       5
18    1018  Employee_18   35           HR       1   69098      1       1
19    1019  Employee_19   26           HR       3  126059      3       3
20    1020  Employee_20   55        Sales       1   56743      1       1
21    1021  Employee_21   24  Engineering       5  122964      5       5
22    1022  Employee_22   52  Engineering       2   52005      2       2
23    1023  Employee_23   54           HR       5   76848      5       5
24    1024  Employee_24   29        Sales       1  107493      1       1
25    1025  Employee_25   47        Sales       3  141296      3       3
26    1026  Employee_26   40  Engineering       3   56350      3       3
27    1027  Employee_27   57        Sales       4  123778      4       4
28    1028  Employee_28   24           HR       1   88453      1       1
29    1029  Employee_29   32        Sales       2   77903      2       2
30    1030  Employee_30   31  Engineering       1   67104      1       1
31    1031  Employee_31   45        Sales       5   98361      5       5
32    1032  Employee_32   25  Engineering       1  135844      1       1
33    1033  Employee_33   36           HR       3  143457      3       3
34    1034  Employee_34   28  Engineering       2   88430      2       2
35    1035  Employee_35   35           HR       4   67336      4       4
36    1036  Employee_36   33        Sales       2  139486      2       2
37    1037  Employee_37   35           HR       4  107955      4       4
38    1038  Employee_38   57  Engineering       4   66261      4       4
39    1039  Employee_39   41        Sales       5  113415      5       5
40    1040  Employee_40   58        Sales       5   72292      5       5
41    1041  Employee_41   25           HR       5  119589      5       5
42    1042  Employee_42   23  Engineering       3  120989      3       3
43    1043  Employee_43   41           HR       4   77007      4       4
44    1044  Employee_44   24           HR       2  111542      2       2
45    1045  Employee_45   29        Sales       5  135408      5       5
46    1046  Employee_46   28        Sales       5  117186      5       5
47    1047  Employee_47   52        Sales       4  142967      4       4
48    1048  Employee_48   53  Engineering       1   92122      1       1
49    1049  Employee_49   29        Sales       4   80870      4       4

In [36]:
df.drop('Bonus', axis=1, inplace=True) # to drop the 'Bonus' column from the DataFrame
df.head()

   emp_id        name  age   department  rating  salary
0    1000  Employee_0   41        Sales       5   70113
1    1001  Employee_1   45           HR       4  133204
2    1002  Employee_2   37  Engineering       3   87700
3    1003  Employee_3   46  Engineering       3   98109
4    1004  Employee_4   54        Sales       1   81980

In [37]:
# Dataset with intentional missing values
data = {
   'Name'  : ['Alice','Bob','Carol','Dave','Eve','Frank'],
   'Age'   : [24, np.nan, 27, 35, np.nan, 40],
   'Salary': [72000, 55000, np.nan, 62000, 48000, np.nan],
   'Dept'  : ['Eng', 'Mkt', 'Eng', None, 'Mkt', 'Eng'],
   'Score' : [85, 90, np.nan, 78, 82, np.nan],
}
df = pd.DataFrame(data)
print("Dataset with missing values:\n", df)

Dataset with missing values:
     Name   Age   Salary Dept  Score
0  Alice  24.0  72000.0  Eng   85.0
1    Bob   NaN  55000.0  Mkt   90.0
2  Carol  27.0      NaN  Eng    NaN
3   Dave  35.0  62000.0  NaN   78.0
4    Eve   NaN  48000.0  Mkt   82.0
5  Frank  40.0      NaN  Eng    NaN

In [38]:
df.isna()

    Name    Age  Salary   Dept  Score
0  False  False   False  False  False
1  False   True   False  False  False
2  False  False    True  False   True
3  False  False   False   True  False
4  False   True   False  False  False
5  False  False    True  False   True

In [39]:
df.isna().sum()

Name      0
Age       2
Salary    2
Dept      1
Score     2
dtype: int64

In [40]:
df['Salary'].mean()

np.float64(59250.0)

In [41]:
df_filled = df.copy()

In [43]:
df_filled['Age']    = df_filled['Age'].fillna(df_filled['Age'].median())
df_filled['Salary'] = df_filled['Salary'].fillna(df_filled['Salary'].mean())
df_filled['Dept']   = df_filled['Dept'].fillna('Unknown')

df_filled

    Name   Age   Salary     Dept  Score
0  Alice  24.0  72000.0      Eng   85.0
1    Bob  31.0  55000.0      Mkt   90.0
2  Carol  27.0  59250.0      Eng    NaN
3   Dave  35.0  62000.0  Unknown   78.0
4    Eve  31.0  48000.0      Mkt   82.0
5  Frank  40.0  59250.0      Eng    NaN

In [44]:
df_filled.groupby('Dept')['Salary'].sum()

Dept
Eng        190500.0
Mkt        103000.0
Unknown     62000.0
Name: Salary, dtype: float64

In [45]:
summary = df.groupby('Dept').agg(
   Count_Emp      = ('Name', 'count'),
   Mean_Salary = ('Salary', 'mean'),
   Max_Score = ('Score', 'max'),
   Avg_Salary  = ('Salary',  'mean'),
).round(1)
print(summary)

      Count_Emp  Mean_Salary  Max_Score  Avg_Salary
Dept
Eng           3      72000.0       85.0     72000.0
Mkt           2      51500.0       90.0     51500.0

In [46]:
df_filled.sort_values('Salary', ascending=True)

    Name   Age   Salary     Dept  Score
4    Eve  31.0  48000.0      Mkt   82.0
1    Bob  31.0  55000.0      Mkt   90.0
5  Frank  40.0  59250.0      Eng    NaN
2  Carol  27.0  59250.0      Eng    NaN
3   Dave  35.0  62000.0  Unknown   78.0
0  Alice  24.0  72000.0      Eng   85.0

In [48]:
df_filled.sort_values(['Salary', 'Age'], ascending=[True, False])

    Name   Age   Salary     Dept  Score
4    Eve  31.0  48000.0      Mkt   82.0
1    Bob  31.0  55000.0      Mkt   90.0
5  Frank  40.0  59250.0      Eng    NaN
2  Carol  27.0  59250.0      Eng    NaN
3   Dave  35.0  62000.0  Unknown   78.0
0  Alice  24.0  72000.0      Eng   85.0